version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-limited
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
