version: "3.8"

services:
  web-server:
    image: nginx:latest
    ports:
      - "8080:80"

  database: # Thêm service mới tại đây
    image: mysql:8.0 # Chỉ định phiên bản 8.0
    restart: always
    environment: # Các biến cấu hình bắt buộc cho MySQL
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword # Bắt buộc phải có pass cho quyền root
    ports:
      - "3306:3306" # Map cổng database mặc định
