services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "172.16.56.250:9092:5672"
      - "172.16.56.250:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "172.16.56.250:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    volumes:
      - mysql-data-v2:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "172.16.56.250:8081:8081"
    environment:
      SERVER_PORT: 8081
      SERVER_ADDRESS: 0.0.0.0
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy

  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    ports:
      - "172.16.56.250:8083:8083"
    environment:
      SERVER_PORT: 8083
      SERVER_ADDRESS: 0.0.0.0
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "172.16.56.250:8084:8084"
    environment:
      SERVER_PORT: 8084
      SERVER_ADDRESS: 0.0.0.0
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "172.16.56.250:8085:8085"
    environment:
      SERVER_PORT: 8085
      SERVER_ADDRESS: 0.0.0.0
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mysql-data-v2:
