version: "3.8"

services:
  app-node:
    build: . # Chỉ định Docker build image từ thư mục hiện tại
    container_name: node-app-container
    ports:
      - "3000:3000" # Map cổng 3000 máy host vào 3000 container
    environment:
      - NODE_ENV=development
